"""add_definition_column

Revision ID: 1e02ebd8d6f2
Revises: 8116758626e6
Create Date: 2026-01-07 19:43:02.571990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e02ebd8d6f2'
down_revision: Union[str, None] = '8116758626e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('definition', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'definition')
    # ### end Alembic commands ###
