"""add_business_status

Revision ID: 528119085a5b
Revises: b4846c6a16e8
Create Date: 2026-01-15 13:11:03.936931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '528119085a5b'
down_revision: Union[str, None] = 'b4846c6a16e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'status')
    # ### end Alembic commands ###
