"""Add resume_payload

Revision ID: 8116758626e6
Revises: 48a3a41ca409
Create Date: 2026-01-07 14:09:04.773434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8116758626e6'
down_revision: Union[str, None] = '48a3a41ca409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_executions', sa.Column('resume_payload', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_executions', 'resume_payload')
    # ### end Alembic commands ###
