"""Add BusinessWhatsAppConfig model

Revision ID: b4846c6a16e8
Revises: 1e02ebd8d6f2
Create Date: 2026-01-13 12:49:46.840791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4846c6a16e8'
down_revision: Union[str, None] = '1e02ebd8d6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
